# Generated by Django 5.0.8 on 2024-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_file_link_message_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
