# Generated by Django 4.1.4 on 2024-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_files_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pdf',
            field=models.FileField(upload_to='files/'),
        ),
    ]
